version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
      POSTGRES_DB: ${DB_NAME:-mydatabase}
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-myuser} -d ${DB_NAME:-mydatabase}"]
      interval: 10s
      timeout: 5s
      retries: 5

  orchestrator:
    image: randao/orchestrator:v0.1.78
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${DB_USER:-myuser}
      DB_PASSWORD: ${DB_PASSWORD:-mypassword}
      DB_NAME: ${DB_NAME:-mydatabase}
      ENVIRONMENT: local
      PATH_TO_WALLET: /app/wallet.json  # Path inside the container
      WALLET_JSON: ${WALLET_JSON}
      PROVIDER_ID: ${PROVIDER_ID}
      DOCKER_NETWORK: backend  # Passing the network name
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - ./wallet.json:/app/wallet.json  # Mount wallet.json into the container

  requester:
    image: randao/requester:v0.1.13
    environment:
      PATH_TO_WALLET: /app/wallet.json  # Path inside the container
      REQUEST_WALLET_JSON: ${REQUEST_WALLET_JSON}
      PROVIDER_ID: ${PROVIDER_ID}
      DOCKER_NETWORK: backend  # Passing the network name
    networks:
      - backend
    volumes:
      - ./wallet.json:/app/wallet.json  # Mount wallet.json into the container

  dbeaver:
    image: dbeaver/cloudbeaver:23.2.0
    environment:
      CB_SERVER_SERVER_PORT: 8080
      CB_SERVER_ADMIN_NAME: "admin"
      CB_SERVER_ADMIN_PASSWORD: "admin123"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    ports:
      - "8081:8978"  # Expose the DBeaver web UI
    volumes:
      - dbeaver-data:/opt/cloudbeaver/workspace

networks:
  backend:
    name: backend  # This will set the network name explicitly
    driver: bridge

volumes:
  pgdata:
    driver: local
  dbeaver-data:
    driver: local
